apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-example
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-example
            image: shreyasgune/kubecron-demo:0.1
          restartPolicy: Never